### ISSUE TITLE
IllegalArgumentException - not attached to window manager

### ISSUE THREAD

**Issue by Nucifera8472** [pubnative/pubnative-android-sdk#5]
**Used versions:** 

'net.pubnative:sdk:2.0.8-master.2567'
'net.pubnative:adapters.admob:11.6.0-2.0.7'
"net.pubnative:sdk.adapter.facebook:2.0.8-4.26.0-master.2567"

**Crash as reported via Crashlytics:**

Fatal Exception: java.lang.IllegalArgumentException: View=net.pubnative.api.core.view.PNAPILoadingView{cdb48ea V.E...... ......ID 0,0-1080,1848} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:382)
       at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:121)
       at net.pubnative.api.core.view.PNAPILoadingViewManager.hide(Unknown Source)
       at net.pubnative.api.core.request.model.PNAPIAdModel.hideLoadingView(Unknown Source)
       at net.pubnative.api.core.request.model.PNAPIAdModel.onURLDrillerFinish(Unknown Source)
       at net.pubnative.URLDriller$4.run(URLDriller.java:242)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:159)
       at android.app.ActivityThread.main(ActivityThread.java:6097)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

Please tell me if you require further information.

**Comment by eros902002** [comment]
Does this happen always? Anyway the sdk and facebook adapter you are using are beta versions. If you are planning on using the actual public version they are the following:
'net.pubnative:sdk:2.0.7'
'net.pubnative:adapters.admob:11.6.0-2.0.7'
'net.pubnative:sdk.adapter.facebook:2.0.7-4.26.0'

**Comment by Nucifera8472** [comment]
I can not reproduce the issue on my devices, but some users seem to have the issue since we updated from version 2.0.5.
We will switch to the official release versions with our next update and check if the issue persists.

**Comment by eros902002** [comment]
We'll take a look into it anyway. Could be an issue with our LoadingView manager. : )
